### ISSUE TITLE
Unable to find download for ImportRegistryHive

### ISSUE THREAD

**Issue by antmar904** [evild3ad/Get-MiniTimeline#1]
Hi.

I am unable to find a site to download the ImportRegistryHive PS module.

**Comment by evild3ad** [comment]
https://blog.redit.name/posts/2015/powershell-loading-registry-hive-from-file.html

**Comment by antmar904** [comment]
It's asking me to request access...

**Comment by evild3ad** [comment]
It seems to be offline.

Download:
[ImportRegistryHive.zip](https://github.com/evild3ad/Get-MiniTimeline/files/15236438/ImportRegistryHive.zip)

**Comment by antmar904** [comment]
Got it.  Thank you!
