### ISSUE TITLE
Could not insert...

### ISSUE THREAD

**Issue by antmar904** [evild3ad/Get-MiniTimeline#2]
Hi.

I've been running this for awhile and it seems to be showing the following in the transcript:

WARNING: Could not insert the 'Description' property at Row 1176957, Column 5
WARNING: Could not insert the 'Time' property at Row 1176958, Column 1
WARNING: Could not insert the 'Source' property at Row 1176958, Column 2
WARNING: Could not insert the 'Host' property at Row 1176958, Column 3
WARNING: Could not insert the 'User' property at Row 1176958, Column 4
WARNING: Could not insert the 'Description' property at Row 1176958, Column 5
WARNING: Could not insert the 'Time' property at Row 1176959, Column 1
WARNING: Could not insert the 'Source' property at Row 1176959, Column 2
WARNING: Could not insert the 'Host' property at Row 1176959, Column 3
WARNING: Could not insert the 'User' property at Row 1176959, Column 4
WARNING: Could not insert the 'Description' property at Row 1176959, Column 5
WARNING: Could not insert the 'Time' property at Row 1176960, Column 1
WARNING: Could not insert the 'Source' property at Row 1176960, Column 2
WARNING: Could not insert the 'Host' property at Row 1176960, Column 3
WARNING: Could not insert the 'User' property at Row 1176960, Column 4
WARNING: Could not insert the 'Description' property at Row 1176960, Column 5
WARNING: Could not insert the 'Time' property at Row 1176961, Column 1

**Comment by evild3ad** [comment]
It is a 5 years old script. ;-)

I have currently no time and motivation to inspect and fix it. Sorry! I will add it to my TODO list and fix it when I find the time...

**Comment by antmar904** [comment]
I hear you.  Thanks

**Comment by evild3ad** [comment]
I have fixed/updated the script...Get-MiniTimeline v0.2 just released. README.md tomorrow! ;-)

**Comment by evild3ad** [comment]
Get-MiniTimeline v0.2 is done. Happy Timelining! ;-)
